### ISSUE TITLE
org-daily-reflection--daily-note-p: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by floli** [emacsomancer/org-roam-daily-reflection#4]
Hello,

just installed org-daily-reflection from MELPA on `GNU Emacs 30.1 (build 1, aarch64-apple-darwin24.3.0, NS appkit-2575.40 Version 15.3.1 (Build 24D70)) of 2025-02-24` on Mac OS.

I execute

```lisp
(setopt org-daily-reflection-dailies-directory "/Users/lil2lr/org/roam/daily/")
(require 'org-daily-reflection)

```

but `(org-daily-reflection-on-last-five-days)` (and other alike commands)

gives me:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  org-daily-reflection--daily-note-p()
  org-daily-reflection(day 4)
  org-daily-reflection-on-last-five-days()
  (progn (org-daily-reflection-on-last-five-days))
  eval((progn (org-daily-reflection-on-last-five-days)) t)
  elisp--eval-last-sexp(nil)
  #f(compiled-function () #<bytecode 0x1866e64735ca>)()
  handler-bind-1(#f(compiled-function () #<bytecode 0x1866e64735ca>) (error) eval-expression--debug)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

Thanks!

**Comment by emacsomancer** [comment]
I'm having trouble reproducing/understanding why `org-daily-reflection-dailies-directory` has a `nil` value after you've set it. (I've tried manually setting my dailies directory in the same way and it works as expected.)

what does `(file-directory-p "/Users/lil2lr/org/roam/daily/")` evaluate to for you, after doing the `setopt`?

**Comment by floli** [comment]
Sorry, for the late reply. I just re-installed the package, but the behavior is unchanged.

`(file-directory-p "/Users/lil2lr/org/roam/daily/")` returns `t`, same for `(file-directory-p org-daily-reflection-dailies-directory)`

**Comment by emacsomancer** [comment]
@floli the latest commit hopefully fixes this.

**Comment by floli** [comment]
Unfortunately, still the same:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  org-daily-reflection--daily-note-p()
  org-daily-reflection(day 4)
  org-daily-reflection-on-last-five-days()
  funcall-interactively(org-daily-reflection-on-last-five-days)
  call-interactively(org-daily-reflection-on-last-five-days record nil)
  command-execute(org-daily-reflection-on-last-five-days record)
  execute-extended-command(nil "org-daily-reflection-on-last-five-days" nil)
  funcall-interactively(execute-extended-command nil "org-daily-reflection-on-last-five-days" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
Upon calling `org-daily-reflection-on-last-five-days`.

Version is `org-daily-reflection-20251120.7`on MELPA.

**Comment by emacsomancer** [comment]
@floli what happens if you set `org-daily-reflection-disable-org-roam-daily-check` to `t`? (just trying to isolate where the problem is).

**Comment by floli** [comment]
This gives me 
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  org-daily-reflection--daily-note-p()
  org-daily-reflection(day 4)
  org-daily-reflection-on-last-five-days()
  (progn (org-daily-reflection-on-last-five-days))
  eval((progn (org-daily-reflection-on-last-five-days)) t)
  elisp--eval-last-sexp(nil)
  #f(compiled-function () #<bytecode 0x1866e65fa792>)()
  handler-bind-1(#f(compiled-function () #<bytecode 0x1866e65fa792>) (error) eval-expression--debug)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

resulting from

```
(setopt org-daily-reflection-dailies-directory "/Users/lil2lr/org/roam/daily/")
(require 'org-daily-reflection)
(setq org-daily-reflection-disable-org-roam-daily-check t)
(setq debug-on-error t)

(org-daily-reflection-on-last-five-days)
```

You have noted that I am no an Apple machine? That might be part of the problem...

**Comment by emacsomancer** [comment]
I guessed from the style of the directory structure that it was likely macOS that was involved, and have wondered about that. But that doesn't seem likely to cause an issue, though I don't have access to the os to test that directly.

~When you `eval` `org-daily-reflection-dailies-directory`, you get the expected directory?  Could you try setting it with `setq` rather than `setopt`, just to see what happens? I realise the latter is more correct, but I'm wondering if setopt's type checking is causing this to end up as nil. (because it sort of looks like that's the issue.)~

~even if setq works, whatever's going on should be fixed. I'm just trying to pinpoint the issue.~

(nevermind the above, see the next comment instead.)

**Comment by emacsomancer** [comment]
Ok. I think I've fixed it in https://github.com/emacsomancer/org-daily-reflection/commit/cb3d76bd09457654c8790a871f8f2f827083339c  [which should be [live on Melpa now](https://melpa.org/#/org-daily-reflection)]

[I realised that I always called the reflection when I had a daily open; I fixed that in the last update, but it depended it the buffer it was called from having a filename, which some buffers, e.g., the scratch buffer, won't; so added a precheck to see if the buffer has an associated filename before checking to see if that filename is a daily.]

**Comment by floli** [comment]
On `org-daily-reflection-20251129.33` I still have that issue:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-nondirectory(nil)
  file-name-base(nil)
  org-daily-reflection--reflect(((day . 4)))
  org-daily-reflection(day 4)
  org-daily-reflection-on-last-five-days()
  funcall-interactively(org-daily-reflection-on-last-five-days)
  call-interactively(org-daily-reflection-on-last-five-days record nil)
  command-execute(org-daily-reflection-on-last-five-days record)
  execute-extended-command(nil "org-daily-reflection-on-last-five-days" " dail re")
  funcall-interactively(execute-extended-command nil "org-daily-reflection-on-last-five-days" " dail re")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by emacsomancer** [comment]
Ah, do you still have `(setq org-daily-reflection-disable-org-roam-daily-check t)` set? You can turn that off now, i.e., set it to `nil` rather than `t`  and it should start working immediately if I'm right about my guess at what's going wrong.

I've pushed a fix that should avoid the issue (if it's what I think it is - being called from a non-file-associated buffer) when `org-daily-reflection-disable-org-roam-daily-check` is set to `t`, though generally speaking it's better to not to disable the check (I had you disable before in case there was some sort of issue I didn't understand about your daily file structure).

**Comment by floli** [comment]
Thanks! I can confirm it works now.

One additional question: `org-daily-reflection-on-last-five-days` opens five windows of the last five days. Within these, are two dailies that did not exist before, i.e. are newly created by that command. Can org-reflection be set to only open existing daily files for reflection?

**Comment by emacsomancer** [comment]
Excellent! 

for the question, yes: set `org-daily-reflection-capture-nascent-files` to `nil`
